kumuluzee:
  name: rso-order
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    etcd:
      hosts: http://etcd:2379
  discovery:
    etcd:
      hosts: http://etcd:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      disk-space-health-check:
        threshold: 100000000

app-properties:
  external-services:
    enabled: false
rest-properties:
  healthy: true;