kumuluzee:
  name: rso-order
  env:
    name: dev
  version: 1.0.
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    etcd:
      hosts: http://etcd:2379
  discovery:
    etcd:
      hosts: http://etcd:2379
    ttl: 60
    ping-interval: 60
app-properties:
  external-services:
    enabled: false