kumuluzee:
  name: rso-order
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    etcd:
      hosts: http://etcd:2379
  discovery:
    etcd:
      hosts: http://etcd:2379
  logs:
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      disk-space-health-check:
        threshold: 100000000
    metrics:
      web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: order-endpoint
        url-pattern: /v1/orders
      - name: order-service
        url-pattern: /v1/orders/service
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="order">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="c322641a-8fb8-4799-9040-d4be6a8cc675-ls.logit.io" port="13437" protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                            <AsyncLogger name="si.fri.rso.projekt.order.api.v1.resources.OrderApi" level="trace" additivity="false" includeLocation="true">
                              <AppenderRef ref="logstash"/>
                            </AsyncLogger>
                        </Loggers>
                    </Configuration>'
app-properties:
  external-services:
    enabled: false
rest-properties:
  healthy: true;